#!/usr/bin/env bash

## Initialise local project for the first time.
##
## Usage: fin init-project

fin composer install
cp ${PROJECT_ROOT}/web/sites/default/example.settings.local.php ${PROJECT_ROOT}/web/sites/default/settings.local.php
fin drush -y si minimal --account-pass=admin --existing-config
fin drush -y deploy
